# .pre-commit-config.yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: run-pytest
        entry: uv run pytest tests/
        language: system
        types: [python]
        pass_filenames: false
