name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "stage"
  release:
    types: [published]

jobs:
  docker:
    name: Build and Push Docker image
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/TrafficGramm/core-backsdk
          tags: |
            type=ref,event=branch,suffix=-{{date 'YYYYMMDDHHmmss' tz='Europe/Moscow'}}
            type=semver,pattern={{version}},event=release
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}